config/routes.rb
Rails.application.routes.draw do
  resources :ocorrencia
  resources :usuarios
  root 'ocorrencia#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ocorrencium.rb
class Ocorrencium < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ocorrencia_controller.rb
class OcorrenciaController < ApplicationController
  before_action :set_ocorrencium, only: [:show, :edit, :update, :destroy]

  # GET /ocorrencia
  # GET /ocorrencia.json
  def index
    @ocorrencia = Ocorrencium.all
  end

  # GET /ocorrencia/1
  # GET /ocorrencia/1.json
  def show
  end

  # GET /ocorrencia/new
  def new
    @ocorrencium = Ocorrencium.new
  end

  # GET /ocorrencia/1/edit
  def edit
  end

  # POST /ocorrencia
  # POST /ocorrencia.json
  def create
    @ocorrencium = Ocorrencium.new(ocorrencium_params)

    respond_to do |format|
      if @ocorrencium.save
        format.html { redirect_to @ocorrencium, notice: 'Ocorrencia criada com sucesso.' }
        format.json { render :show, status: :created, location: @ocorrencium }
      else
        format.html { render :new }
        format.json { render json: @ocorrencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ocorrencia/1
  # PATCH/PUT /ocorrencia/1.json
  def update
    respond_to do |format|
      if @ocorrencium.update(ocorrencium_params)
        format.html { redirect_to @ocorrencium, notice: 'Ocorrencia atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @ocorrencium }
      else
        format.html { render :edit }
        format.json { render json: @ocorrencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ocorrencia/1
  # DELETE /ocorrencia/1.json
  def destroy
    @ocorrencium.destroy
    respond_to do |format|
      format.html { redirect_to ocorrencia_url, notice: 'Ocorrencia excluida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ocorrencium
      @ocorrencium = Ocorrencium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ocorrencium_params
      params.require(:ocorrencium).permit(:foto, :descricao, :data, :localizacao)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario criado com sucesso.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nome, :email, :telefone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ocorrencia_helper.rb
module OcorrenciaHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelpPets - Usuarios</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="margin-top: 0px; margin-left: 0px; margin-right: 0px; magin-bottom: 0px">
    <%= yield %>
  </body>
</html>

app/views/ocorrencia/_form.html.erb
<%= form_with(model: ocorrencium, local: true) do |form| %>
  <% if ocorrencium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ocorrencium.errors.count, "error") %> prohibited this ocorrencium from being saved:</h2>

      <ul>
      <% ocorrencium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :foto %>
    <%= form.text_field :foto, id: :ocorrencium_foto %>
  </div>

  <div class="field">
    <%= form.label :descreva_o_ocorrido %>
    <%= form.text_area :descricao, id: :ocorrencium_descricao %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select :data, id: :ocorrencium_data %>
  </div>

  <div class="field">
    <%= form.label :onde_ocorreu %>
    <%= form.text_field :localizacao, id: :ocorrencium_localizacao %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ocorrencia/edit.html.erb
<h1>Editing Ocorrencium</h1>

<%= render 'form', ocorrencium: @ocorrencium %>

<%= link_to 'Exibir', @ocorrencium %> |
<%= link_to 'Voltar', ocorrencia_path %>

app/views/ocorrencia/index.html.erb
<div style="text-align: right; background: #4682b4; height: 50px">
  <br>
<%= link_to 'Novo Usuário', new_usuario_path, class: 'css_class', style: 'color:#FFFFFF' %>
&nbsp;&nbsp;&nbsp;
<%= link_to 'Nova Ocorrência', new_ocorrencium_path, class: 'css_class', style: 'color:#FFFFFF' %>
</div>
<br>
<center><img src="https://pbs.twimg.com/media/DOXsXnhXkAE-O1S.jpg" alt="Logo HelpPets"></center>
<br>
<br>
<br>
<div style="text-align: center">
<h1>Ocorrências</h1>
  <p> Encontrou um pet abandonado ou em situação de risco? Cadastre-se no site e registre sua ocorrência. </p>
<br>

<% @ocorrencia.each do |ocorrencium| %>
<div>
  <%= image_tag(ocorrencium.foto, size:"500x370", :alt => "Dog na bad") %>
<br>  
  <%= ocorrencium.descricao %>
  <br>
   <%= ocorrencium.localizacao %>
  <br>
  <%= ocorrencium.data %>
  <br>
  <%= link_to 'Exibir', ocorrencium %>
  <%= link_to 'Editar', edit_ocorrencium_path(ocorrencium) %>
  <%= link_to 'Excluir', ocorrencium, method: :delete, data: { confirm: 'Tem certeza?' } %>
 <br> 
 <br>
 <br>
</div>
<% end %>
</div>
<br>
<div style= "text-align: center; background: #4682b4; height: 180px">
  <br>
<h2><font style="color:white"> Feito com <3 no Rails Gils BH 2017</font></h2>
  <p><font style="color:white">Por Lorrany, Mariane, Marina, Priscila e Sandra.</font></p>
 <font style="color:white"><p>Tutoras: Edlaine e Nadja. </font></p>
</div>

app/views/ocorrencia/new.html.erb
<h1>Nova Ocorrencia</h1>

<%= render 'form', ocorrencium: @ocorrencium %>

<%= link_to 'Voltar', ocorrencia_path %>

app/views/ocorrencia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Foto:</strong>
  <%= @ocorrencium.foto %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @ocorrencium.descricao %>
</p>

<p>
  <strong>Data:</strong>
  <%= @ocorrencium.data %>
</p>

<p>
  <strong>Localizacao:</strong>
  <%= @ocorrencium.localizacao %>
</p>

<%= link_to 'Editar', edit_ocorrencium_path(@ocorrencium) %> |
<%= link_to 'Voltar', ocorrencia_path %>

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :usuario_nome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :usuario_email %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :usuario_telefone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editando o Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.telefone %></td>
        <td><%= link_to 'Exibir', usuario %></td>
        <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Excluir', usuario, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>Novo Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Voltar', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @usuario.telefone %>
</p>

<%= link_to 'Editar', edit_usuario_path(@usuario) %> |
<%= link_to 'Voltar', usuarios_path %>